apiVersion: v1
kind: Service
metadata:
  name: libsys-service
spec:
  type: NodePort
  selector:
    app: libsys
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30080 #Minikube IP at this port